### ISSUE TITLE
Fully Support Legere Theme

### ISSUE THREAD

**Issue by thatrobotdev** [chingu-coders/owl-24#5]
Support the Legere theme located [here](https://www.reddit.com/r/themes/comments/6c51r1/legere_a_clean_and_easy_to_navigate_reddit_theme/).

 - [x] Button on page, that is intended for going to the Legere theme.
 - [x] Legere theme page.
 - [x] Legere's code on theme page
 - [x] Step by step instructions with pictures to guide people on how they can install the theme.

**Comment by jamesjpk123** [comment]
Image loaded inside of the project.

**Comment by jamesjpk123** [comment]
Legere code has been added in, but the design is flawed. I don't how to do this from here, so I'm asking help from the turtles-project-party.

**Comment by jamesjpk123** [comment]
Redesign of site is helping with this issue, progress is continuing.
